### PR TITLE
Update ignore list based on M2 build

### PR DESCRIPTION
**Pull request by JinhangZhang**

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@jasonkatonica @llxia FYI

**Comment by llxia** [comment]
This should be delivered to openj9 branch and cherry-pick into v0.46.0-release. @JasonFengJ9 could you please confirm? Thanks

**Comment by llxia** [comment]
On a related note, should we also update https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt, so that future openjdk repo will have a default list?

**Comment by JasonFengJ9** [comment]
> This should be delivered to openj9 branch and cherry-pick into v0.46.0-release. @JasonFengJ9 could you please confirm?

Yes, that's the usual practice assuming the change applies to the default (`openj9`) branch as well.

**Comment by JasonFengJ9** [comment]
> On a related note, should we also update https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt, so that future openjdk repo will have a default list?

Right, a PR should be opened against the headstream first, i.e., https://github.com/ibmruntimes/openj9-openjdk-jdk, then backported to earlier Java-level extension repos like current JDK22.

**Comment by JinhangZhang** [comment]
Pushing to the openj9 branch and Opening a PR in the headstream

**Pull request closed without merging**
