### PR TITLE
Re-enable FIPS140-3 failures

### PR DESCRIPTION
**Pull request by JinhangZhang**

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@llxia @jasonkatonica As discussed, re-enable update where test ignores were removed in https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/83 & https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/85.

**Comment by JinhangZhang** [comment]
@JasonFengJ9 @pshipton Please help to merge

**Comment by JasonFengJ9** [comment]
@jasonkatonica please review.

**Comment by jasonkatonica** [comment]
Looks good to me.

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by JasonFengJ9** [comment]
@JinhangZhang pls create a PR for 0.46 branch.

**Pull request merged**
